A3
aul12/SicherheitInItSystemen pull request #8
Opened 2019-12-08 10:23 UTC by TarikEnderes

2019-12-10 21:37 UTC, aul12 commented
Kannst du dann alle Leute assignen wenn der fertig ist?

2019-12-17 13:22 UTC, TarikEnderes commented
Vergesse ich jedes mal -.-

2019-12-17 13:24 UTC, aul12 requested changes

2019-12-17 13:24 UTC, aul12 commented on group17-s2/a3/a.txt
> +Stattdessen muss den Capability-Sets Perimitted und Effective die Capability CAP_NET_RAW hinzugefügt werden.
```suggestion
Stattdessen muss den Capability-Sets Permitted und Effective die Capability CAP_NET_RAW hinzugefügt werden. 
```

2019-12-17 13:24 UTC, aul12 commented on group17-s2/a3/a.txt
> +Das ist mit dem Befehl "sudo setcap cap_net_raw=ep /bin/ping" möglich.
```suggestion
Das ist mit dem Befehl "sudo setcap cap_net_raw=ep $(which ping)" möglich.
```
Dann hast du da nicht den Pfad Hardgecoded

2019-12-17 13:24 UTC, aul12 commented on group17-s2/a3/b.txt
> +Im Manual Linux (linux.net/man/7/capabilities) gibt es für die Capability CAP_NET_BIND_SERVICE folgende Beschreibung: "Bind a socket to Internet domain privileged ports (port numbers less than 1024)"
Nicht eher Linux Manual (`man capabilities`)

2019-12-17 13:24 UTC, aul12 commented on group17-s2/a3/b.txt
> +Die Datei, der die Capability zugeweisen werden muss, ist /bin/nc.openbsd.
Vielleicht noch erwähnen auf welcher Distro, nur Ubuntu hat dieses dubiose Alternatives System

2019-12-17 13:24 UTC, aul12 commented on group17-s2/a3/b.txt
> +Der vollständige Befehl zum Hinzufügen der Capability zu netcat ist daher: "sudo setcap cap_net_bind_service=ep /bin/nc.openbsd".
```suggestion
Der vollständige Befehl zum Hinzufügen der Capability zu netcat ist daher: "sudo setcap cap_net_bind_service=ep $(readlink -f $(which netcat))".
```

2019-12-17 13:35 UTC, TarikEnderes commented on group17-s2/a3/b.txt
> +Im Manual Linux (linux.net/man/7/capabilities) gibt es für die Capability CAP_NET_BIND_SERVICE folgende Beschreibung: "Bind a socket to Internet domain privileged ports (port numbers less than 1024)"
Die Internetseite kann man auch ohne Linux anschauen. Deswegen finde ich das besser.

2019-12-17 13:37 UTC, Timmifixedit approved these changes

2019-12-17 13:37 UTC, aul12 commented on group17-s2/a3/b.txt
> +Im Manual Linux (linux.net/man/7/capabilities) gibt es für die Capability CAP_NET_BIND_SERVICE folgende Beschreibung: "Bind a socket to Internet domain privileged ports (port numbers less than 1024)"
Dann aber immerhin Linux Manual

2019-12-17 13:47 UTC, aul12 approved these changes

2019-12-17 13:47 UTC, merged